[package]
name = "hello_vulkan"
version = "0.1.0"
authors = ["michey <aleksandr.mihailov@protonmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[[bin]]
name = "ressha"
path = "src/ressha/main.rs"

[lib]
name="kikansha"
path= "src/kikansha/lib.rs"

[profile.release]
debug = true


[dependencies]
vulkano = "0.20.0"
vk-sys = "0.5.3"
vulkano-shaders = "0.20.0"
gltf = "0.15.2"
winit = "0.24"
vulkano-win = "0.20.0"
nalgebra = "0.24.0"
nalgebra-glm = "0.10.0"
png = "0.16.8"
log = "0.4"
log4rs = "1.0.0"
clap = "2.33.3"